# Generated by Django 3.1 on 2021-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Kosmos', 'Kosmos'), ('Klimat', 'Klimat'), ('Technologia', 'Technologia')], max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
