# Generated by Django 3.1 on 2021-03-16 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('higher_author', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('higher_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.comment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='podcast',
            name='background',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.comment')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.podcast')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcast.podcast'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
