# Generated by Django 3.1 on 2021-04-03 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20210317_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='file',
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
