# Generated by Django 3.1 on 2021-04-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20210403_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='podcast_code',
            new_name='code',
        ),
    ]
